### ISSUE TITLE
PCB layout differs from photo

### ISSUE THREAD

**Issue by algavrik** [Tek-User/Tektronix-GPIB-Download#2]
PCB layout on OSHPARK differs from the real photo of PCB in the project. On OSHPARK PCB resistors are on the bottom side (arduino) of the board, but on the real photo I can see resistors on the top side of PCB (GPIB). Can you clarify?

**Comment by Tek-User** [comment]
I will check.  It has been a couple of years since I worked with this.  

-Tony

**Comment by Tek-User** [comment]
The through hole resistors can be placed on either side.   For simplicity during design I drew everything on the same side but for construction they can be placed on either side
